htd_lync12:
  - host: 192.168.1.133
    zones:
      - Master Bedroom
      - Master Bathroom
      - Bedroom 1
      - Kitchen
      - Living Room
      - Fireplace Porch
      - Deck at Living Room
      - Deck at Master Bedroom
      - Upstairs Den
      - Bedroom 2
      - Bedroom 3
      - Bonus Room

    sources:
      - NA 1
      - NA 2
      - NA 3
      - Bluetooth
      - NA 5
      - NA 6
      - NA 7
      - NA 8
      - NA 9
      - NA 10
      - NA 11
      - NA 12
      - NA 13
      - NA 14
      - NA 15
      - Airplay
      - Alexa
      - MP3 Player
